# All source downloads are performed by setup-workflow-deps.ps1, hash checked.
# Configuring/building the application never accesses the network.
function(portbridge_setup_workflow_dependencies)
  if(TARGET portbridge_workflow_protocol)
    return()
  endif()
  get_filename_component(_root "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/.." ABSOLUTE)
  set(PORTBRIDGE_WORKFLOW_DEPS "${_root}/.deps/workflow" CACHE PATH "Locked workflow dependencies")
  set(_deps "${PORTBRIDGE_WORKFLOW_DEPS}")
  foreach(_entry cpr-1.14.2/CMakeLists.txt curl-8.16.0/CMakeLists.txt c-ares-1.34.5/CMakeLists.txt boost_1_89_0/boost/beast.hpp openssl-install/include/openssl/ssl.h)
    if(NOT EXISTS "${_deps}/${_entry}")
      message(FATAL_ERROR "Missing workflow dependency ${_entry}; run scripts/setup-workflow-deps.ps1 first")
    endif()
  endforeach()
  set(OPENSSL_ROOT_DIR "${_deps}/openssl-install")
  set(OPENSSL_USE_STATIC_LIBS TRUE)
  # Never accept an unrelated development-PATH OpenSSL installation.
  set(OPENSSL_INCLUDE_DIR "${_deps}/openssl-install/include" CACHE PATH "" FORCE)
  set(OPENSSL_SSL_LIBRARY "${_deps}/openssl-install/lib64/libssl.a" CACHE FILEPATH "" FORCE)
  set(OPENSSL_CRYPTO_LIBRARY "${_deps}/openssl-install/lib64/libcrypto.a" CACHE FILEPATH "" FORCE)
  find_package(OpenSSL 3.5.4 EXACT REQUIRED)
  set(BUILD_SHARED_LIBS OFF)
  set(BUILD_STATIC_LIBS ON)
  foreach(_option BUILD_CURL_EXE BUILD_TESTING BUILD_EXAMPLES BUILD_LIBCURL_DOCS BUILD_MISC_DOCS ENABLE_CURL_MANUAL CURL_USE_LIBPSL CURL_USE_PKGCONFIG CURL_USE_LIBSSH2 USE_LIBIDN2 USE_NGHTTP2 CURL_ZLIB CURL_BROTLI CURL_ZSTD CURL_USE_SCHANNEL)
    set(${_option} OFF)
  endforeach()
  set(HTTP_ONLY ON)
  set(CURL_DISABLE_COOKIES ON)
  set(CURL_DISABLE_WEBSOCKETS ON)
  set(CURL_USE_OPENSSL ON)
  set(ENABLE_THREADED_RESOLVER OFF)
  set(ENABLE_ARES ON)
  set(CURL_DISABLE_DOH ON)
  # c-ares keeps DNS asynchronous and cancellable without spawning a detached
  # getaddrinfo thread for each retired HTTP request.
  set(CMAKE_POLICY_DEFAULT_CMP0077 NEW)
  set(CARES_STATIC ON)
  set(CARES_SHARED OFF)
  set(CARES_BUILD_TOOLS OFF)
  set(CARES_BUILD_TESTS OFF)
  set(CARES_INSTALL ON)
  set(CARES_THREADS OFF)
  set(CMAKE_AUTOMOC OFF)
  add_subdirectory("${_deps}/c-ares-1.34.5" "${CMAKE_BINARY_DIR}/workflow-deps/cares" EXCLUDE_FROM_ALL)
  export(TARGETS c-ares NAMESPACE c-ares:: FILE "${CMAKE_BINARY_DIR}/workflow-deps/cares/c-ares-build-targets.cmake")
  set(CARES_LIBRARY c-ares)
  set(CARES_INCLUDE_DIR "${_deps}/c-ares-1.34.5/include")
  # Scope Qt autogen out of dependency targets.
  set(CMAKE_AUTOMOC OFF)
  add_subdirectory("${_deps}/curl-8.16.0" "${CMAKE_BINARY_DIR}/workflow-deps/curl" EXCLUDE_FROM_ALL)
  set(CPR_USE_EXISTING_CURL_TARGET ON)
  set(CPR_FORCE_OPENSSL_BACKEND ON)
  set(CPR_CURL_USE_LIBPSL OFF)
  set(CPR_BUILD_TESTS OFF)
  set(CPR_BUILD_TESTS_SSL OFF)
  set(CPR_CURL_NOSIGNAL ON)
  add_subdirectory("${_deps}/cpr-1.14.2" "${CMAKE_BINARY_DIR}/workflow-deps/cpr" EXCLUDE_FROM_ALL)
  find_package(Threads REQUIRED)
  add_library(portbridge_workflow_protocol STATIC
    "${_root}/include/portbridge/workflow_protocol.hpp"
    "${_root}/src/protocol/workflow_protocol.cpp"
    "${_root}/src/protocol/http_client.cpp"
    "${_root}/src/protocol/ws_plain.cpp"
    "${_root}/src/protocol/ws_tls.cpp")
  set_target_properties(portbridge_workflow_protocol PROPERTIES AUTOMOC ON)
  target_compile_features(portbridge_workflow_protocol PUBLIC cxx_std_17)
  target_include_directories(portbridge_workflow_protocol PUBLIC "${_root}/include" PRIVATE "${_root}/src/protocol")
  target_include_directories(portbridge_workflow_protocol SYSTEM PRIVATE "${_deps}/boost_1_89_0")
  target_compile_definitions(portbridge_workflow_protocol PRIVATE BOOST_ASIO_NO_DEPRECATED BOOST_BEAST_USE_STD_STRING_VIEW)
  target_link_libraries(portbridge_workflow_protocol PUBLIC Qt6::Core PRIVATE cpr::cpr OpenSSL::SSL OpenSSL::Crypto Threads::Threads)
  if(WIN32)
    target_compile_definitions(portbridge_workflow_protocol PRIVATE _WIN32_WINNT=0x0A00 WIN32_LEAN_AND_MEAN NOMINMAX)
    target_link_libraries(portbridge_workflow_protocol PRIVATE ws2_32 mswsock crypt32 bcrypt)
  endif()
  if(MINGW)
    target_compile_options(portbridge_workflow_protocol PRIVATE -Wall -Wextra -Wpedantic)
  endif()
  # Beast's template instantiations are memory intensive; serialize in Ninja.
  set_property(GLOBAL APPEND PROPERTY JOB_POOLS workflow_protocol_compile=1)
  set_property(TARGET portbridge_workflow_protocol PROPERTY JOB_POOL_COMPILE workflow_protocol_compile)
endfunction()
